user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

bird:
    resource: "@BirdBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group