# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: [ROLE_ADMIN, ROLE_SUPER_USER, ROLE_USER]
        ROLE_SUPER_USER: [ROLE_SUPER_USER, ROLE_USER]
        ROLE_USER: []

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: .*
            context: user
            form_login:
                provider: fos_userbundle
                login_path: /connexion
                check_path: /verification
                failure_path: null
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /deconnexion
            anonymous:    true

    access_control:
        - { path: ^/connexion$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reinitialiser, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/nouvelle_observation, role: ROLE_USER }
        - { path: ^/dernieres_observations, role: ROLE_SUPER_USER }
        - { path: ^/administration, role: ROLE_ADMIN }