# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  search_bird:
        class: BirdBundle\service\SearchService
        arguments: ["@doctrine.orm.entity_manager", "@form.factory"]

  add_bird:
      class: BirdBundle\service\AddBird
      arguments: ["@doctrine.orm.entity_manager", "@form.factory"]

  app.menu_builder:
      class: BirdBundle\Menu\MenuBuilder
      arguments: ["@knp_menu.factory"]
      tags:
          - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }