# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:

  search_bird:
        class: BirdBundle\Service\SearchService
        arguments: ["@doctrine.orm.entity_manager", "@form.factory"]

  app.image_uploader:
          class: BirdBundle\Service\UploadFile
          arguments: ['%images_directory%']

  app.doctrine_images_listener:
          class: BirdBundle\EventListener\ImageUploadListener
          arguments: ['@app.image_uploader']
          tags:
              - { name: doctrine.event_listener, event: prePersist }
              - { name: doctrine.event_listener, event: preUpdate }
  add_bird:
        class: BirdBundle\Service\AddBird
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", '@app.image_uploader']
