# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  search_bird:
        class: BirdBundle\Service\SearchService
        arguments: ["@doctrine.orm.entity_manager", "@form.factory"]

  validate_bird:
        class: BirdBundle\Service\ValidateBirdService
        arguments: ["@doctrine.orm.entity_manager", "@form.factory"]

  app.image_uploader:
          class: BirdBundle\Service\UploadFile
          arguments: ['%images_directory%']

  app.doctrine_images_listener:
          class: BirdBundle\EventListener\ImageUploadListener
          arguments: ['@app.image_uploader']
          tags:
              - { name: doctrine.event_listener, event: prePersist }
              - { name: doctrine.event_listener, event: preUpdate }

  app.exception_listener:
      class: BirdBundle\EventListener\WrongRouteListener
      arguments:
          router: "@router"
      tags:
          - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

  add_bird:
        class: BirdBundle\Service\AddBird
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", '@app.image_uploader', '@security.token_storage', '@security.authorization_checker']

  app.menu_builder:
      class: BirdBundle\Menu\MenuBuilder
      arguments: ["@knp_menu.factory", "@security.authorization_checker"]
      tags:
          - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }